//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatice_ikkan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Blog_id { get; set; }
        public string Blog_Baslık { get; set; }
        public string Blog_Ozet { get; set; }
        public string Blog_Acıklama { get; set; }
        public string Blog_Resmi { get; set; }
        public int Yonetici_id { get; set; }
        public int Uye_id { get; set; }
    
        public virtual Uyeler Uyeler { get; set; }
        public virtual Yoneticiler Yoneticiler { get; set; }
    }
}
