//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatice_ikkan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favoriler
    {
        public int Favori_No { get; set; }
        public int Uye_id { get; set; }
        public int Urun_id { get; set; }
    
        public virtual Urunler Urunler { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
