//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatice_ikkan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public int Kayıt_No { get; set; }
        public Nullable<int> Siparis_id { get; set; }
        public short Siparis_Adet { get; set; }
        public System.DateTime Siparis_Tarihi { get; set; }
        public int Uye_id { get; set; }
        public int Urun_id { get; set; }
    
        public virtual Urunler Urunler { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
