//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatice_ikkan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int Yorum_id { get; set; }
        public string Yorum_Yazar { get; set; }
        public string Yorum_Acıklama { get; set; }
    }
}
